version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: |
          docker --version
          docker login --username $DOCKER_USER --password $DOCKER_PASS https://docker-registry.sportlink.com
      - run: |
          rm -rf bundles
          rm -rf tempbundles
          mkdir tempbundles
          mkdir bundles
          IMAGE=docker-registry.sportlink.com/sportlink-replication
          BASEIMAGE=dexels/navajo-streams
          BASEBUILDNR=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/navajo-streams?circle-token=${CIRCLE_TOKEN}&limit=100&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "package_navajo")][0].build_num')
          SPORTLINKLIBRARYVERSION=$(curl -s "https://circleci.com/api/v1.1/project/github/Dexels/sportlink.library/tree/master?circle-token=${CIRCLE_TOKEN}&offset=0&filter=successful" | jq '[.[]| select(.workflows.job_name == "build")][0].build_num')
          curl -s -o tempbundles/sportlinklibrary_p2.zip "https://${SPORTLINKLIBRARYVERSION}-8196922-gh.circle-artifacts.com/0/sportlinklibrary_p2.zip?circle-token=${CIRCLE_TOKEN}"
          unzip tempbundles/sportlinklibrary_p2.zip -d tempbundles
          ls -l tempbundles
          echo "After tempbundles"
          find tempbundles -name *teamorder* | xargs -I {} cp {} bundles
          ls -l bundles
          echo "After bundles"
          BASETAG=${BASEMINORVERSION}.$BASEBUILDNR
          echo "Tagging for: ${IMAGE}:${IMAGEVERSION}.${CIRCLE_BUILD_NUM}  onto super: ${BASEIMAGE}.${BASETAG}"
          docker build . --build-arg VERSION=${BASETAG} -t ${IMAGE}:${IMAGEVERSION}.${CIRCLE_BUILD_NUM} -t ${IMAGE}:latest
          docker push ${IMAGE}:${IMAGEVERSION}.${CIRCLE_BUILD_NUM}
          docker push ${IMAGE}:latest
